#!/usr/bin/env bash

set -e

cd ~

show="Johnny Doom"
year="$(date -d 'now' '+%Y')"
name="$(date -d 'now' '+%Y-%m-%d %A')"

curl $STREAM_URL --max-time 10 --output "$name.mp3"

mp3val "$name.mp3" -f -nb

eyeD3 --year=$year --title="$name" --album="$show" --artist="Kerrang! Radio" --genre=Rock --add-image=./icon.png:ICON "$name.mp3"

# upload to Google drive
