#!/usr/bin/env bash

cd ~

year="$(date -d 'now' '+%Y')"
name="$(date -d 'now' '+%Y-%m-%d')"

curl ${STREAM_URL} --max-time ${DURATION} --output "${name}.mp3"

mp3val "${name}.mp3" \
    -f \
    -nb         # Fix errors & remove backup files created during file rebuilding

curl ${MP3_ICON} --output mp3-icon

eyeD3 --release-year="${year}" \
    --recording-date="${name}" \
    --title="${name}" \
    --album="${SHOW_TITLE}" \
    --artist="${STATION_NAME}" \
    --genre="${GENRE}" \
    --add-image=./mp3-icon:ICON "${name}.mp3"

echo "CONFIGFILE_VERSION=2.0
OAUTH_APP_KEY=${DROPBOX_APP_KEY}
OAUTH_APP_SECRET=${DROPBOX_APP_SECRET}
OAUTH_REFRESH_TOKEN=${DROPBOX_REFRESH_TOKEN}" > .dropbox_uploader

bash ./dropbox_uploader.sh -f .dropbox_uploader upload "${name}.mp3" "${name}.mp3"
